name = "xiuxian-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "xiuxian-codes"
database_id = "6697002b-8132-4055-99a7-4955fd945924"  # 创建 D1 后填入
